In [1]:
import  numpy as np


# expand_dims
add a new dimention to ndarray

In [30]:
a= np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

----- possitive value as axis--------

In [31]:
a0=np.expand_dims(a,axis=0) # 0 is position to add the dimention
a0.shape


(1, 2, 4)

In [33]:
a0

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [36]:
a1=np.expand_dims(a,axis=1)
a1.shape
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [37]:
a2=np.expand_dims(a,axis=2)
a2

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

----- negative value as axis--------

negative value corresponds to the last dimention and you can specify the position from behind

In [41]:
a_1=np.expand_dims(a,axis=-1)
a_1 # here this is same as axis=2 becuse 2 from behind is -1

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])